const ASCII_CODE_OF_LOWER_A = 97;
const ASCII_CODE_OF_LOWER_Z = 122;
const MATCH_NEGATIVE_NUMBER_REGEX = /-\d+/g;
const ERRORS = {
  NEGATIVES_NOT_ALLOWED: "Negatives not allowed",
};

module.exports = {
  ASCII_CODE_OF_LOWER_A,
  ASCII_CODE_OF_LOWER_Z,
  MATCH_NEGATIVE_NUMBER_REGEX,
  ERRORS,
};
